apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    metadata:
      labels:
       name: app-pod
    spec:
      containers:
        - name: container-wp
          image: wordpress
          ports:
            - containerPort: 80