- name: download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: a+x
  become: true

- name: download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: a+x
  become: true

- name: Minikube start
  shell: minikube start

- name: Deployment
  shell: kubectl create -f /home/jakeline/git/desafio-devops/kubernetes/app/deployment.yaml 

- name: Service
  shell: kubectl create -f /home/jakeline/git/desafio-devops/kubernetes/app/service.yaml 

# - name: configurações kubectl
#   get_url:
#     url: http://example.com/path/file.conf
#     dest: /etc/foo.conf
#     mode: 0440